apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: iscsi-provisioner
  namespace: iscsi-provisioner
spec:
  selector:
    matchLabels:
      app: iscsi-provisioner
  serviceName: "iscsi-tgt-1"
  replicas: 1
  template:
    metadata:
      labels:
        app: iscsi-provisioner
    spec:
      containers:
        - name: iscsi-provisioner
          imagePullPolicy: Always
          securityContext:
            privileged: true
          image: aosqe/iscsi-provisioner:latest
          args:
            - "start"
          env:
            - name: PROVISIONER_NAME
              value: iscsi-targetd
            - name: LOG_LEVEL
              value: debug
            - name: TARGET
              value: "#TARGET#"
          volumeMounts:
          - mountPath: /lib/modules
            name: kernel
          - mountPath: /iscsi_disks
            name: iscsi-disks
      serviceAccount: iscsi-provisioner
      volumes:
      - hostPath:
          path: /lib/modules
        name: kernel
      - hostPath:
          path: /mnt/iscsi_disks
        name: iscsi-disks
