kind: DeploymentConfig
apiVersion: v1
metadata:
  name: iscsi-provisioner
  namespace: iscsi-provisioner
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: iscsi-provisioner
    spec:
      containers:
        - name: iscsi-provisioner
          imagePullPolicy: Always
          securityContext:
            privileged: true
          image: aosqe/iscsi-provisioner:latest
          args:
            - "start"
          env:
            - name: PROVISIONER_NAME
              value: iscsi-targetd
            - name: LOG_LEVEL
              value: debug
            - name: TARGET_PORT
              value: "3260"
            - name: TARGET_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
          - mountPath: /lib/modules
            name: kernel
          - mountPath: /iscsi_disks
            name: iscsi-disks
          hostNetwork: true
          hostPID: true
      serviceAccount: iscsi-provisioner
      volumes:
      - hostPath:
          path: /lib/modules
        name: kernel
      - hostPath:
          path: /sysroot/iscsi_disks
        name: iscsi-disks
